name: Generate Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  # Allows manual triggers via the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Generates the snake files using the Platane/snk action
      - name: Generate Snake Files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Deploys the generated animations to an isolated 'output' branch
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
